### ISSUE TITLE
Show status message in challenge step

### ISSUE THREAD

**Issue by nikriek** [projectsecure/projectsecure-client#39]
Given I want solve the passphrase challenge, I would first try to enter a basic word, I expect to receive a message why the word is not suitable as passphrase.

**Comment by nikriek** [comment]
This scenario and it's generalization to other challenges is currently not reflected.

**Comment by nicoknoll** [comment]
Already implemented. But server implementation still missing: https://github.com/projectsecure/projectsecure-api/issues/67
